# modified from source
# https://github.com/datastax/cass-operator/blob/26ad52bfc8f450852f5573fa2904a5df407ce2d3/operator/example-cassdc-yaml/cassandra-3.11.6/example-cassdc-minimal.yaml
---
# Sized to work on 3 k8s workers nodes with 1 core / 4 GB RAM
# See neighboring example-cassdc-full.yaml for docs for each parameter
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
    name: dc1
spec:
    clusterName: cluster1
    serverType: cassandra
    serverVersion: "3.11.6"
    serverImage: datastax/cassandra-mgmtapi-3_11_6:v0.1.0 # Fallout specific requirement, serverImage must be set
    managementApiAuth:
        insecure: {}
    size: 1 # Fallout's default KIND test runs with a single node
    storageConfig:
        cassandraDataVolumeClaimSpec:
            storageClassName: server-storage
            accessModes:
                - ReadWriteOnce
            resources:
                requests:
                    storage: 5Gi
    config:
        jvm-options:
            initial_heap_size: "800M"
            max_heap_size: "800M"
